---
-
  package:
    name: "{{item}}"
    state: present
  name: "Install test dependencies"
  tags:
    - install_dependencies
  with_items: "{{ test_required_libs  }}"
-
  group:
    name: "{{ tomcat_group }}"
    system: true
  name: "Create tomcat group"
  tags:
    - create_tomcat_group
-
  name: "Create tomcat user"
  tags:
    - create_tomcat_user
  user:
    createhome: true
    generate_ssh_key: true
    group: "{{ tomcat_group }}"
    home: "{{tomcat_home_dir}}"
    name: "{{ tomcat_user }}"
    shell: /bin/bash
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    system: true
-
  file:
    mode: 0755
    path: "{{tomcat_home_dir}}"
    state: directory
  name: "Set tomcat home directory permission"
  tags:
    - set_tomcat_home_permission
-
  become_user: "{{ tomcat_user }}"
  name: "Add ssh config"
  tags:
    - add_ssh_config
  template:
    dest: "{{tomcat_home_dir}}/.ssh/config"
    mode: 256
    src: ssh-config.j2
-
  name: "Download and extract tomcat archive"
  tags:
    - download_extract
  unarchive:
    copy: false
    dest: "{{tomcat_home_dir}}"
    extra_opts:
      - "--strip-components=1"
    group: "{{ tomcat_group }}"
    owner: "{{ tomcat_user }}"
    src: "{{ tomcat_url }}"
-
  file:
    group: "{{ tomcat_group }}"
    owner: "{{ tomcat_user }}"
    path: "{{tomcat_home_dir}}/{{item}}"
    recurse: true
  name: "Make the tomcat user the owner of the webapps, work, temp, and logs directories"
  tags:
    - web_work_temp_logs_perm
  with_items:
    - webapps
    - work
    - temp
    - logs
-
  file:
    mode: g+r
    path: "{{tomcat_home_dir}}/conf"
    recurse: true
    state: directory
  name: "Grant Tomcat group read access to the conf directory"
  tags:
    - conf_g+r_perm
-
  file:
    mode: g+x
    path: "{{tomcat_home_dir}}/conf"
    state: directory
  name: "Grant Tomcat group execute access to the conf directory itself"
  tags:
    - conf_g+x_perm
-
  become_user: "{{ tomcat_user }}"
  name: "Create tomcat-users.xml"
  tags:
    - apply_tomcat_user_role
  template:
    dest: "{{tomcat_home_dir}}/conf/tomcat-users.xml"
    src: tomcat-users.xml.j2
-
  name: "Replace ip restriction of manager & host-manager role"
  tags:
    - remove_tomcat_role_ip_restriction
  template:
    dest: "{{ item }}"
    src: context.xml.j2
  with_items:
    - "{{tomcat_home_dir}}/webapps/host-manager/META-INF/context.xml"
    - "{{tomcat_home_dir}}/webapps/manager/META-INF/context.xml"
-
  file:
    dest: "{{ tomcat_app_path }}"
    src: "{{ tomcat_home_dir }}"
    state: link
  name: "Symlink Tomcat to current version"
  tags:
    - create_app_link
-
  name: "Create systemd service script for Tomcat"
  tags:
    - systemd_script_install
  template:
    dest: /lib/systemd/system/tomcat.service
    src: tomcat.service.j2
