---
# Variable setup.
- name: Include OS-Specific variables
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  #when: ansible_pkg_mgr == "yum"

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  #when: ansible_pkg_mgr == "apt"
