---
# file: oracle-java/tasks/debian/main.yml
#
# Task file to install Oracle Java Development Kit in a system with a Debian based Linux distribution.
#

- name: Add java ppa repository
  apt_repository:
    repo=ppa:webupd8team/java
    state=present
  become: yes
  tags: [add_ppa]

- block:
  - name: Ensure the webupd8 launchpad apt repository key is present
    apt_key:
      id=0xC2518248EEA14886
      keyserver=keyserver.ubuntu.com
      state=present
    become: yes

  - name: Ensure the webupd8 launchpad apt repository is present
    apt_repository:
      repo="{{ item }} http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main"
      update_cache=yes
      state=present
    with_items:
      - deb
      - deb-src
    become: yes

  when: ansible_distribution == 'Debian'

- name: Set license as accepted
  debconf: name='oracle-java{{ oracle_java_version }}-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  become: yes
  tags: [accept_license]

- name: Ensure Java is installed
  apt:
    name="oracle-java{{ oracle_java_version }}-installer"
    state={{ oracle_java_state }}
    cache_valid_time={{ oracle_java_cache_valid_time }}
    update_cache=yes
  become: yes
  tags: [install_java]

- name: Export JAVA_HOME java_build_path
  shell: "export JAVA_HOME={{ oracle_java_home }}"
  become: yes
  tags: [export_java_home]
