---
#
# Default variables for Debian-based Linux distributions.
#
oracle_java_version: 8

oracle_java_cache_valid_time: 3600

oracle_java_home: "/usr/lib/jvm/java-{{ oracle_java_version }}-oracle"

oracle_java_state: latest
